config/routes.rb
Rails.application.routes.draw do
  root 'users#profile'
  get 'users/profile'
  get 'teams/index'

#resolve these
  devise_for :users
  as :user do
    get 'users/profile', :to => 'users#profile', :as => :user_root
  end

  resources :teams
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :players
  post '/send_message', to: 'message#send_message'
  post '/receive', to: 'message#receive_message'

  resources :games
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/availability.rb
class Availability < ApplicationRecord
  belongs_to :game
  belongs_to :player
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :matches
  has_many :teams, through: :matches
  has_many :availabilities
  scope :chronological, -> { order(:date) }
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :team
  belongs_to :game
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :team
  belongs_to :player
end

app/models/player.rb
class Player < ApplicationRecord
  has_many :memberships
  has_many :teams, through: :memberships
  has_many :availabilities
  has_many :games, through: :teams
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :user, optional: true
  has_many :matches
  has_many :memberships
  has_many :players, through: :memberships
  has_many :games, through: :matches
end

app/models/user.rb
class User < ApplicationRecord
  has_many :teams
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  #before_action :authenticate_user!
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
  end

  def new
    @game = Game.new
    @teams = Team.all
  end

  def create
    @game = Game.new(game_params)
    @teams = Team.all

    if @game.save
      redirect_to @game
    else
      render 'new'
    end
  end

  def edit
    @game = Game.find(params[:id])
  end

  def update
    @game = Game.find(params[:id])

    if @game.update(game_params)
      redirect_to @game
    else
      render 'edit'
    end
  end

  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    redirect_to games_path
  end

  private
  def game_params
    params.require(:game).permit(:date, :location, :home_team, :away_team)
  end

end

app/controllers/message_controller.rb
class MessageController < ApplicationController
 skip_before_action :verify_authenticity_token

  def send_message
    game = Game.all.chronological.first
    boot_twilio
    Player.all.each do |player|
      @client.messages.create(
        from: '+16195676513',
        to: player.phone_number,
        body: "Your #{player.teams.name} has a Game at #{game.location} on #{game.date}! Please reply 'yes' if you can make it, and 'no' if you are unable to come."
        )
    end
  end


  def receive_message
    message_body = (params['Body'] || '').downcase
    from_number = params['From']
    player = Player.find_by(phone_number: from_number.slice(1..-1))
    game = player.games.chronological.first
    availability = Availability.new(player: player, game: game)


    case message_body
    when 'yes'
      response = 'OK! We will see you then!'
      availability.can_participate = 'yes'
    when 'no'
      response = 'OK! thanks for letting us know.'
      availability.can_participate = 'no'
    else
      response = "I am sorry I did not catch that. Please reply 'yes' if you can make it, and 'no if you cannot."
    end

    availability.save!
    boot_twilio
    sms = @client.messages.create(
      from: '+16195676513',
      to: from_number,
      body: response
      )
  end

  private

  def boot_twilio
    account_sid = ENV['TWILIO_SID']
    auth_token = ENV['TWILIO_TOKEN']
    @client = Twilio::REST::Client.new account_sid, auth_token
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
     @players = Player.all
  end

  def new
    @player = Player.new
    @teams = Team.all
  end

  def create
    @player = Player.new(player_params)
    @team = Team.find(player_params[:team_id])
    @team.memberships.create(player: @player)

    if @player.save
      redirect_to @player, notice: "#{@player.first_name} #{@player.last_name} was successfully added."
    else
      render :new, status: 422
    end
  end

  def edit
    @player = Player.find(params[:id])
    @teams = Team.all
  end

  def update
      @player = Player.find(params[:id])
    if @player.update(player_params)
      redirect_to @player
    else
      render 'edit'
    end
  end

  def destroy
    player = Player.find(params[:id])
    player.destroy
    redirect_to players_url, notice: 'Player was successfully removed.'
  end

  def show
    @player = Player.find(params[:id])
  end

  private
    def player_params
      params.require(:player).permit(:first_name, :last_name, :phone_number, :team_id)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    @teams = Team.all
  end

  def show
    @team = Team.find(params[:id])
  end

  def new
    @team = Team.new
  end

  def create
    @team = Team.new(team_params)

    if @team.save
      redirect_to @team
    else
      render 'new'
    end
  end

  def edit
    @team = Team.find(params[:id])
  end

  def update
    @team = Team.find(params[:id])

    if @team.update(team_params)
      redirect_to @team
    else
      render 'edit'
    end
  end

  def destroy
    @team = Team.find(params[:id])
    @team.destroy

    redirect_to teams_path
  end

  private
  def team_params
    params.require(:team).permit(:name, :sport, :number_required_to_play, :user_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile
    current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def email_to_showname(email)
    email = email.split('@')
    email[0]
  end
end

app/views/games/_form.html.erb
<%= form_for @game do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@game.errors.count, "error") %> prohibited
        this game from being saved:
      </h2>
      <ul>
        <% @game.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </p>

  <p>
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </p>

  <p>
    <%= f.label :home_team %><br>
    <%= f.select(:home_team, @teams.map{ |team| [team.name, team.name] }) %>
  </p>

  <p id="teams_drop_down">
    <%= f.label :away_team %><br>
    <%= f.select(:away_team, @teams.map{ |team| [team.name, team.name] }) %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/games/edit.html.erb
<h1>Edit game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Listing games</h1>
<table>
  <tr>
    <th class="blue-grey lighten-4">Game location</th>
    <th class="blue-grey lighten-4">Game date and time</th>
    <th class="blue-grey lighten-4">Home</th>
    <th class="blue-grey lighten-4">Away</th>
    <th class="blue-grey lighten-4"></th>
    <th class="blue-grey lighten-4"></th>
    <th class="blue-grey lighten-4"></th>
    <th class="blue-grey lighten-4"></th>
  </tr>

  <% @games.each do |game| %>
    <tr>
      <td><%= game.location %></td>
      <td><%= game.date %></td>
      <td><%= game.home_team %></td>
      <td><%= game.away_team %></td>
      <td><%= link_to 'Show', game_path(game) %></td>
      <td><%= link_to 'Edit', edit_game_path(game) %></td>
      <td><%= link_to 'Destroy', game_path(game),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<button class="btn waves-effect waves-light right white" type="submit" name="action"> <%= link_to 'New game', new_game_path %>
  </button>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p>
  <strong>Game Location:</strong>
  <%= @game.location %>
</p>

<p>
  <strong>Date and Time:</strong>
  <%= @game.date %>
</p>

<p>
  <strong>Home:</strong>
  <%= @game.home_team %>
</p>

<p>
  <strong>Away:</strong>
  <%= @game.away_team %>
</p>
<form action="/send_message" method="POST">
  <input type="submit" value="Send a message" />
</form>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/layouts/_nav.html.erb
<nav>
  <div class="nav-wrapper blue-grey darken-1">
    <h3 class="brand-logo center"><%= link_to('TeamTracker', teams_path) %></h3>
    <ul id="nav-mobile" class="right hide-on-med-and-down" >
      <% if user_signed_in? %>
      <li><%= link_to("#{current_user.email}", user_root_path) %></li>
      <li><%= link_to('Games', games_path) %></li>
      <li><%= link_to('Teams', teams_path) %></li>
      <li><%= link_to('Players', players_path) %></li>
      <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
      <% else %>
      <li><%= link_to('Login', new_user_session_path)  %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeamTracker</title>
    <%= csrf_meta_tags %>

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
    <%= render "layouts/nav" %>
  <body>
    <%= yield %>
  </body>
</html>

app/views/players/_form.html.erb
<%= form_for @player do |f| %>

  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@player.errors.count, "error") %> prohibited
        this player from being saved:
      </h2>
      <ul>
        <% @player.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </p>

  <p>
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </p>

  <p>
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </p>

  <p>
    <%= f.label :team %><br>
    <%= f.select(:team_id, @teams.map{ |team| [team.name, team.id] }) %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/players/edit.html.erb
<h1>Edit Player Info</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<h1>Player list</h1>
<table>
  <tr>
    <th class="blue-grey lighten-4">First Name</th>
    <th class="blue-grey lighten-4">Last Name</th>
    <th class="blue-grey lighten-4">Phone Number</th>
    <th class="blue-grey lighten-4">Teams they are on</th>
    <th class="blue-grey lighten-4"></th>
    <th class="blue-grey lighten-4"></th>
    <th class="blue-grey lighten-4"></th>
  </tr>

  <% @players.each do |player| %>
    <tr>
      <td><%= player.first_name %></td>
      <td><%= player.last_name %></td>
      <td><%= player.phone_number %></td>
      <% player.teams.each do |team| %>
        <td><%= team.name %></td>
      <% end %>
      <td><%= link_to 'Show', player_path(player) %></td>
      <td><%= link_to 'Edit', edit_player_path(player) %></td>
      <td><%= link_to 'Destroy', player_path(player),
              method: :delete,
              data: { confirm: "Are you sure you want to remove #{player.first_name} #{player.last_name}" } %></td>
    </tr>
  <% end %>
</table>
<button class="btn waves-effect waves-light right white" type="submit" name="action"> <%= link_to 'New player', new_player_path %>
  </button>

app/views/players/new.html.erb
<h1>New player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p>
  <strong>First Name:</strong>
  <%= @player.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @player.last_name %>
</p>

<p>
  <strong> Phone number:</strong>
  <%= @player.phone_number %>
</p>

<p>
  <strong>Teams <%= @player.first_name %> plays with:</strong>
  <ul>
  <% @player.teams.each do |team| %>
  <li><%= team.name %></li>
  </ul>
  <% end %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>

app/views/users/profile.html.erb
<h1><%=email_to_showname(current_user.email)%>'s profile</h1>
<h2>Teams you manage:</h2>
<% current_user.teams.each do |team| %>
<ul>
  <li><%= link_to("#{team.name}" , team) %>
  </li>
</ul>
<% end %>

Your email: <%=current_user.email%><br>